name: Debug OpenAI Key

on:
  workflow_dispatch:  # הפעלה ידנית בלבד

jobs:
  check-key:
    runs-on: ubuntu-latest
    steps:
      - name: Debug OPENAI_API_KEY length
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo ">>> OPENAI_API_KEY length is: ${#OPENAI_API_KEY}"
          if [ -z "$OPENAI_API_KEY" ]; then
            echo "❌ OPENAI_API_KEY is empty!"
            exit 1
          else
            echo "✅ OPENAI_API_KEY is set."
          fi
