import os
import time
import random
import requests
import schedule
from requests.auth import HTTPBasicAuth

# Configuration
WP_URL      = "https://whellthyvibe.com"
WP_USER     = "autoai"
WP_PASSWORD = "bhUj b0Og Yk5N jO9z 5l3B ix2N"

API_BASE = f"{WP_URL.rstrip('/')}/wp-json/wp/v2"

# Predefined topics list
TOPICS = [
    "Proper nutrition for athletes",
    "Effective home workouts",
    "Beginner fitness routines",
    "Cardio training for endurance",
    "Bodyweight exercises",
    "Core workouts at home",
    "Daily exercise schedule",
    "Mental health through sport",
    "Post-workout recovery strategies",
    "Importance of sleep for athletes"
]

auth = HTTPBasicAuth(WP_USER, WP_PASSWORD)


def create_post(title: str):
    payload = {"title": title, "status": "publish"}
    try:
        r = requests.post(f"{API_BASE}/posts", auth=auth, json=payload)
        r.raise_for_status()
        print("Posted (title only):", title)
    except Exception as e:
        print("Post creation failed:", e)


def job():
    topic = random.choice(TOPICS)
    print("Generating title-only post for topic:", topic)
    create_post(topic)

# initial run and schedule
if __name__ == "__main__":
    job()
    schedule.every().hour.do(job)
    while True:
        schedule.run_pending()
        time.sleep(1)
