    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai==0.28 requests schedule httpx

      - name: Run auto_poster
        env:
          WP_URL:           ${{ secrets.WP_URL }}
          WP_USER:          ${{ secrets.WP_USER }}
          WP_PASSWORD:      ${{ secrets.WP_PASSWORD }}
          OPENAI_API_KEY:   ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "OPENAI_API_KEY length: ${#OPENAI_API_KEY}"
          python auto_poster.py
