# File: .github/workflows/post.yml
name: Auto Post

on:
  schedule:
    # כל שעה בדקה 0
    - cron: '0 * * * *'
  workflow_dispatch:  # מאפשר הרצה ידנית

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # פין לגרסה 0.28 שתומכת ב־ChatCompletion.create
          pip install openai==0.28.0 requests schedule httpx

      - name: Run auto_poster
        env:
          WP_URL:         ${{ secrets.WP_URL }}
          WP_USER:        ${{ secrets.WP_USER }}
          WP_PASSWORD:    ${{ secrets.WP_PASSWORD }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python auto_poster.py
