name: Auto Post

on:
  schedule:
    # כל שעה בדקה 0
    - cron: '0 * * * *'
  workflow_dispatch:    # הרצה ידנית

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

            - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # מגבילים לגרסה 0.28 שמכילה את openai.ChatCompletion.create
          pip install openai==0.28.0 requests schedule httpx --force-reinstall

      - name: Debug OPENAI_API_KEY
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo ">>> OPENAI_API_KEY length: ${#OPENAI_API_KEY}"
          # אם זה 0 — ה-Secret לא נטען כראוי

      - name: Run auto_poster
        env:
          WP_URL:         ${{ secrets.WP_URL }}
          WP_USER:        ${{ secrets.WP_USER }}
          WP_PASSWORD:    ${{ secrets.WP_PASSWORD }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python auto_poster.py
