name: Auto Post
on:
  schedule:
    - cron: '0 */1 * * *'  # כל שעה
  workflow_dispatch:
jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: python-version: '3.x'
      - run: |
          python -m pip install --upgrade pip
          pip install openai requests pillow
      - env:
          WP_URL: ${{ secrets.WP_URL }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_PASS: ${{ secrets.WP_PASS }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python auto_poster.py
